### ISSUE TITLE
Blending effects aren't correctly reflected in the canvas

### ISSUE THREAD

**Issue by itsdouges** [WICG/html-in-canvas#47]
From my explorations I've noticed that these styles don't get correctly reflected in the canvas:

- `mix-blend-mode` (seems to be applied twice, something's going on)
- `backdrop-filter` (not applied at all)

Inside the canvas: the circle (mix-blend-mode) has way more contrast than expected, and the rectangle (backdrop-filter) just isn't applied at all
<img width="485" height="324" alt="Image" src="https://github.com/user-attachments/assets/0ffa4939-d114-440a-840c-93a111bf4bd3" />

What it looks like in the DOM
<img width="505" height="363" alt="Image" src="https://github.com/user-attachments/assets/c44e988e-3ecb-435f-a0ce-df8cfdd221e8" />

**Comment by schenney-chromium** [comment]
We're aware of the backdrop filter problem. I'll get to it once more pressing privacy issues are fixed.

I'll also look into the blend mode issues. Those we were not aware of.

**Comment by itsdouges** [comment]
Thanks, if it helps this is the file that replicates the issues https://app.paper.design/file/01K5QJ41FY12Z59M84SQTC4RHD

**Comment by schenney-chromium** [comment]
Thanks for the example. I was going to ask you for it. Can't say how much I appreciate your contributions.

**Comment by itsdouges** [comment]
Hey folks to make it easier I've made a sandbox https://codesandbox.io/p/sandbox/fznycv?file=%2Fsrc%2FApp.tsx where you can switch between DOM and html-in-canvas

Looks like `mix-blend-mode` is already fixed in Chrome canary, can you confirm? Great work!

**Comment by schenney-chromium** [comment]
I'm still seeing the blend mode incorrect. I'll look into both of these issues this week.

**Comment by itsdouges** [comment]
is there any known issues with using backdrop-filters currently? I'm experiencing an issue.

no backdrop filter - positioned as expected

<img width="574" height="431" alt="Image" src="https://github.com/user-attachments/assets/025d7676-1666-43d2-a18f-6cc40cfb2e2b" />

with backdrop filter - position offset, text disappears

<img width="575" height="431" alt="Image" src="https://github.com/user-attachments/assets/8d4693f3-e315-458c-878a-e55bc57988e6" />

i've made a replication here: https://stackblitz.com/edit/vitejs-vite-nmfb6ekf?file=src%2FApp.tsx

backdrop filter is working in general though which is great.

**Comment by schenney-chromium** [comment]
There was a bug with the backdrop filter position that was fixed a few days ago. It's also a bit tricky in that it it will not filter the canvas background color itself, and the exact things included in the backdrop are sensitive to layering of the content in some non-obvious (to me) ways. But the most common cases work now.

**Comment by itsdouges** [comment]
> and the exact things included in the backdrop are sensitive to layering of the content in some

would you say the example I linked above is a common case? text below the backdrop not appearing / element with backdrop filter not taking its absolute position into account correctly.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/7a11192e-345d-4a34-940f-bc4faae43572" />

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/46ef755b-e600-4a52-bad9-52d9058619ef" />

**Comment by AndrewPrifer** [comment]
Related issue: if you apply box shadow to the element, the blur area includes the area of the shadow.

**Comment by schenney-chromium** [comment]
> Related issue: if you apply box shadow to the element, the blur area includes the area of the shadow.

Thanks for letting up know. I assume you're talking about the blur applied as a canvas filter. Otherwise I'm not sure of which blur you are referring to.

If so I think the behavior is expected, though I won't argue that it is the best behavior. My thinking is that the canvas filter applies to the entire painted result from the DOM content, so any shadow, filter, etc will be filtered by the canvas filter effect. The same effect doesn't happen if you apply a CSS blur filter and a CSS shadow because the code that generates the commands for painting understands how the filters should combine.

**Comment by AndrewPrifer** [comment]
@schenney-chromium I might be misunderstanding what you mean by canvas filter, I meant applying both backdrop-filter: blur() and box-shadow to the same element within the html rendered to canvas. In this case, the blur will extend to the bounds of the shadow instead of the border box. I will create a repro.

By the way, only slightly related, I also just saw that box-shadow tanks the fps proportionally to its size similarly to how linear-gradients used to before it was fixed in canary just recently.

**Comment by schenney-chromium** [comment]
Is the box-shadow performance problem on Mac? From memory we tried to fix that but it caused a regression in some other way.

I'll look into the blur issue. Any repro example would be helpful, thanks.

**Comment by progers** [comment]
I was able to reproduce the issue using the stackblitz.com link. While we've fixed many backdrop-filter bugs, this one is not yet fixed. I've filed https://crbug.com/503307127 for this.

Note: there have been a few changes in the API shape that require a small update to the demo to use the new `paint` event. See: https://github.com/WICG/html-in-canvas?tab=readme-ov-file#basic-example for an example. I'd recommend using Chrome Canary if possible.

**Comment by AndrewPrifer** [comment]
I have repros for 3 issues in the latest canary (Version 149.0.7796.0 (Official Build) canary (arm64)):

Setting a background color on an element fixes positioning (at least in this repro, in other instances I did get weird clipping with backdrop filters even with gb on). Removing the background color makes it move to the top left with the text element disappearing: https://stackblitz.com/edit/vitejs-vite-95v7a6yb?file=src%2FApp.tsx

Box shadow expands backdrop filter area. Shadows otherwise seem to "fix" the positioning similarly to applying background: https://stackblitz.com/edit/vitejs-vite-dqfm6io9?file=src%2FApp.tsx

Shadow performance. I forgot to mention, the issue only applies to inset shadow, regular box shadows are fine. https://stackblitz.com/edit/vitejs-vite-ldruxijw?file=src%2FApp.tsx,src%2Fwebgpu-utils.ts,src%2Findex.css,src%2Fmain.tsx

The performance issue only shows for a sufficiently large texture. In my example, small windows still manage to hover around 60 fps, but maximizing it on my Studio Display (5k monitor), takes it down to 23 fps during scroll.

**Comment by itsdouges** [comment]
@progers hey things are looking much better, I've been doing some tests this morning. two issues:

## 1. backdrop filters aren't respecting border radius

**screenshot through html-in-canvas**

<img  height="400" alt="Image" src="https://github.com/user-attachments/assets/a2f6f669-b1c8-45ac-893f-7dd60c4bbc42" />

**screencap from the paper canvas**

<img height="400" alt="Image" src="https://github.com/user-attachments/assets/15d294aa-80de-4d22-8995-6a691e2b2466" />

here's a reproduction: https://stackblitz.com/edit/vitejs-vite-ajydzlrs?file=src%2Fmain.tsx,src%2FApp.tsx&terminal=dev

## 2. the original issue above where backdrop filters mixed with effects aren't working, the backdrop filter is dropped

**screenshot through html-in-canvas**

<img height="400" alt="Image" src="https://github.com/user-attachments/assets/1d6e8509-d947-409a-ac0e-3b0d9df676ac" />

**screencap from the paper canvas**

<img height="400" alt="Image" src="https://github.com/user-attachments/assets/084a1e1b-b64a-446b-b88f-95fc4a4463af" />

**Comment by itsdouges** [comment]
just an update for anyone at home: "1. backdrop filters aren't respecting border radius" looks to be fixed in the latest chrome! happy days.

the original issue however is.. still an issue, reproduction here: https://stackblitz.com/edit/vitejs-vite-uvzeszyu?file=package.json,src%2FApp.tsx&terminal=dev

html-in-canvas
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/d87d65bc-ea17-425b-8fff-56ecaa799e90" />

vs. dom

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/33fcc953-c1b4-4e6b-a543-8962f0d19efb" />
